# Generated by Django 2.2.6 on 2019-11-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='tempo',
            field=models.FloatField(),
        ),
    ]
