# Generated by Django 2.2.6 on 2019-11-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_auto_20191117_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='campus',
            field=models.CharField(choices=[('IFPB - AREIA', 'IFPB - CAMPUS: AREIA'), ('IFPB - CABEDELO', 'IFPB - CAMPUS: CABEDELO'), ('IFPB - CABEDELO - CENTRO', 'IFPB - CAMPUS: CABEDELO - CENTRO'), ('IFPB - CAJAZEIRAS', 'IFPB - CAMPUS: CAJAZEIRAS'), ('IFPB - CAMPINA GRANDE', 'IFPB - CAMPUS: CAMPINA GRANDE'), ('IFPB - CATOLÉ DO ROCHA', 'IFPB - CAMPUS: CATOLÉ DO ROCHA'), ('IFPB - ESPERANÇA', 'IFPB - CAMPUS: ESPERANÇA'), ('IFPB - GUARABIRA', 'IFPB - CAMPUS: GUARABIRA'), ('IFPB - ITABAIANA', 'IFPB - CAMPUS: ITABAIANA'), ('IFPB - ITAPORANGA', 'IFPB - CAMPUS: ITAPORANGA'), ('IFPB - JOÃO PESSOA', 'IFPB - CAMPUS: JOÃO PESSOA'), ('IFPB - JOÃO PESSOA', 'IFPB - CAMPUS: MANGABEIRA'), ('IFPB - MONTEIRO', 'IFPB - CAMPUS: MONTEIRO'), ('IFPB - PATOS', 'IFPB - CAMPUS: PATOS'), ('IFPB - PEDRAS DE FOGO', 'IFPB - CAMPUS: PEDRAS DE FOGO'), ('IFPB - PICUÍ', 'IFPB - CAMPUS: PICUÍ'), ('IFPB - PRINCESA ISABEL', 'IFPB - CAMPUS: PRINCESA ISABEL'), ('IFPB - SANTA LUZIA', 'IFPB - CAMPUS: SANTA LUZIA'), ('IFPB - SANTA RITA', 'IFPB - CAMPUS: SANTA RITA'), ('IFPB - SOLEDADE', 'IFPB - CAMPUS: SOLEDADE'), ('IFPB - SOUSA', 'IFPB - CAMPUS: SOUSA')], max_length=30),
        ),
    ]
