# Generated by Django 2.2.6 on 2019-11-20 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0005_auto_20191120_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='value_penal_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='value_penal_10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='value_penal_11',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='value_penal_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='value_penal_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='value_penal_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='value_penal_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='value_penal_6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='value_penal_7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='value_penal_8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='value_penal_9',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='penalidade_1',
            field=models.CharField(choices=[('Nenhuma', 'Nenhuma'), ('Tocar o robô', 'Tocar o robô'), ('O robô tocou em qualquer borda da pista', 'O robô tocou em qualquer borda da pista'), ('Não passar por dentro do túnel', 'Não passar por dentro do túnel'), ('Quando o robô não conseguir subir a rampa 30 graus', 'Quando o robô não conseguir subir a rampa'), ('Quando o robô não conseguir descer a rampa 30 graus', 'Quando o robô não conseguir descer a rampa'), ('Não separar ou separar incorretamente algum objeto da zona de coleta seletiva', 'Não separar ou separar incorretamente algum objeto da zona de coleta seletiva'), ('Robô virar de lado ou de ponta cabeça', 'Robô virar de lado ou de ponta cabeça'), ('Robô destruir a pista', 'Robô destruir a pista'), ('Não acessar a Área de Coleta Seletiva', 'Não acessar a Área de Coleta Seletiva'), ('DNS - Did Not Start', 'DNS - Did Not Start')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='penalidade_10',
            field=models.CharField(choices=[('Nenhuma', 'Nenhuma'), ('Tocar o robô', 'Tocar o robô'), ('O robô tocou em qualquer borda da pista', 'O robô tocou em qualquer borda da pista'), ('Não passar por dentro do túnel', 'Não passar por dentro do túnel'), ('Quando o robô não conseguir subir a rampa 30 graus', 'Quando o robô não conseguir subir a rampa'), ('Quando o robô não conseguir descer a rampa 30 graus', 'Quando o robô não conseguir descer a rampa'), ('Não separar ou separar incorretamente algum objeto da zona de coleta seletiva', 'Não separar ou separar incorretamente algum objeto da zona de coleta seletiva'), ('Robô virar de lado ou de ponta cabeça', 'Robô virar de lado ou de ponta cabeça'), ('Robô destruir a pista', 'Robô destruir a pista'), ('Não acessar a Área de Coleta Seletiva', 'Não acessar a Área de Coleta Seletiva'), ('DNS - Did Not Start', 'DNS - Did Not Start')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='penalidade_11',
            field=models.CharField(choices=[('Nenhuma', 'Nenhuma'), ('Tocar o robô', 'Tocar o robô'), ('O robô tocou em qualquer borda da pista', 'O robô tocou em qualquer borda da pista'), ('Não passar por dentro do túnel', 'Não passar por dentro do túnel'), ('Quando o robô não conseguir subir a rampa 30 graus', 'Quando o robô não conseguir subir a rampa'), ('Quando o robô não conseguir descer a rampa 30 graus', 'Quando o robô não conseguir descer a rampa'), ('Não separar ou separar incorretamente algum objeto da zona de coleta seletiva', 'Não separar ou separar incorretamente algum objeto da zona de coleta seletiva'), ('Robô virar de lado ou de ponta cabeça', 'Robô virar de lado ou de ponta cabeça'), ('Robô destruir a pista', 'Robô destruir a pista'), ('Não acessar a Área de Coleta Seletiva', 'Não acessar a Área de Coleta Seletiva'), ('DNS - Did Not Start', 'DNS - Did Not Start')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='penalidade_2',
            field=models.CharField(choices=[('Nenhuma', 'Nenhuma'), ('Tocar o robô', 'Tocar o robô'), ('O robô tocou em qualquer borda da pista', 'O robô tocou em qualquer borda da pista'), ('Não passar por dentro do túnel', 'Não passar por dentro do túnel'), ('Quando o robô não conseguir subir a rampa 30 graus', 'Quando o robô não conseguir subir a rampa'), ('Quando o robô não conseguir descer a rampa 30 graus', 'Quando o robô não conseguir descer a rampa'), ('Não separar ou separar incorretamente algum objeto da zona de coleta seletiva', 'Não separar ou separar incorretamente algum objeto da zona de coleta seletiva'), ('Robô virar de lado ou de ponta cabeça', 'Robô virar de lado ou de ponta cabeça'), ('Robô destruir a pista', 'Robô destruir a pista'), ('Não acessar a Área de Coleta Seletiva', 'Não acessar a Área de Coleta Seletiva'), ('DNS - Did Not Start', 'DNS - Did Not Start')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='penalidade_3',
            field=models.CharField(choices=[('Nenhuma', 'Nenhuma'), ('Tocar o robô', 'Tocar o robô'), ('O robô tocou em qualquer borda da pista', 'O robô tocou em qualquer borda da pista'), ('Não passar por dentro do túnel', 'Não passar por dentro do túnel'), ('Quando o robô não conseguir subir a rampa 30 graus', 'Quando o robô não conseguir subir a rampa'), ('Quando o robô não conseguir descer a rampa 30 graus', 'Quando o robô não conseguir descer a rampa'), ('Não separar ou separar incorretamente algum objeto da zona de coleta seletiva', 'Não separar ou separar incorretamente algum objeto da zona de coleta seletiva'), ('Robô virar de lado ou de ponta cabeça', 'Robô virar de lado ou de ponta cabeça'), ('Robô destruir a pista', 'Robô destruir a pista'), ('Não acessar a Área de Coleta Seletiva', 'Não acessar a Área de Coleta Seletiva'), ('DNS - Did Not Start', 'DNS - Did Not Start')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='penalidade_4',
            field=models.CharField(choices=[('Nenhuma', 'Nenhuma'), ('Tocar o robô', 'Tocar o robô'), ('O robô tocou em qualquer borda da pista', 'O robô tocou em qualquer borda da pista'), ('Não passar por dentro do túnel', 'Não passar por dentro do túnel'), ('Quando o robô não conseguir subir a rampa 30 graus', 'Quando o robô não conseguir subir a rampa'), ('Quando o robô não conseguir descer a rampa 30 graus', 'Quando o robô não conseguir descer a rampa'), ('Não separar ou separar incorretamente algum objeto da zona de coleta seletiva', 'Não separar ou separar incorretamente algum objeto da zona de coleta seletiva'), ('Robô virar de lado ou de ponta cabeça', 'Robô virar de lado ou de ponta cabeça'), ('Robô destruir a pista', 'Robô destruir a pista'), ('Não acessar a Área de Coleta Seletiva', 'Não acessar a Área de Coleta Seletiva'), ('DNS - Did Not Start', 'DNS - Did Not Start')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='penalidade_5',
            field=models.CharField(choices=[('Nenhuma', 'Nenhuma'), ('Tocar o robô', 'Tocar o robô'), ('O robô tocou em qualquer borda da pista', 'O robô tocou em qualquer borda da pista'), ('Não passar por dentro do túnel', 'Não passar por dentro do túnel'), ('Quando o robô não conseguir subir a rampa 30 graus', 'Quando o robô não conseguir subir a rampa'), ('Quando o robô não conseguir descer a rampa 30 graus', 'Quando o robô não conseguir descer a rampa'), ('Não separar ou separar incorretamente algum objeto da zona de coleta seletiva', 'Não separar ou separar incorretamente algum objeto da zona de coleta seletiva'), ('Robô virar de lado ou de ponta cabeça', 'Robô virar de lado ou de ponta cabeça'), ('Robô destruir a pista', 'Robô destruir a pista'), ('Não acessar a Área de Coleta Seletiva', 'Não acessar a Área de Coleta Seletiva'), ('DNS - Did Not Start', 'DNS - Did Not Start')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='penalidade_6',
            field=models.CharField(choices=[('Nenhuma', 'Nenhuma'), ('Tocar o robô', 'Tocar o robô'), ('O robô tocou em qualquer borda da pista', 'O robô tocou em qualquer borda da pista'), ('Não passar por dentro do túnel', 'Não passar por dentro do túnel'), ('Quando o robô não conseguir subir a rampa 30 graus', 'Quando o robô não conseguir subir a rampa'), ('Quando o robô não conseguir descer a rampa 30 graus', 'Quando o robô não conseguir descer a rampa'), ('Não separar ou separar incorretamente algum objeto da zona de coleta seletiva', 'Não separar ou separar incorretamente algum objeto da zona de coleta seletiva'), ('Robô virar de lado ou de ponta cabeça', 'Robô virar de lado ou de ponta cabeça'), ('Robô destruir a pista', 'Robô destruir a pista'), ('Não acessar a Área de Coleta Seletiva', 'Não acessar a Área de Coleta Seletiva'), ('DNS - Did Not Start', 'DNS - Did Not Start')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='penalidade_7',
            field=models.CharField(choices=[('Nenhuma', 'Nenhuma'), ('Tocar o robô', 'Tocar o robô'), ('O robô tocou em qualquer borda da pista', 'O robô tocou em qualquer borda da pista'), ('Não passar por dentro do túnel', 'Não passar por dentro do túnel'), ('Quando o robô não conseguir subir a rampa 30 graus', 'Quando o robô não conseguir subir a rampa'), ('Quando o robô não conseguir descer a rampa 30 graus', 'Quando o robô não conseguir descer a rampa'), ('Não separar ou separar incorretamente algum objeto da zona de coleta seletiva', 'Não separar ou separar incorretamente algum objeto da zona de coleta seletiva'), ('Robô virar de lado ou de ponta cabeça', 'Robô virar de lado ou de ponta cabeça'), ('Robô destruir a pista', 'Robô destruir a pista'), ('Não acessar a Área de Coleta Seletiva', 'Não acessar a Área de Coleta Seletiva'), ('DNS - Did Not Start', 'DNS - Did Not Start')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='penalidade_8',
            field=models.CharField(choices=[('Nenhuma', 'Nenhuma'), ('Tocar o robô', 'Tocar o robô'), ('O robô tocou em qualquer borda da pista', 'O robô tocou em qualquer borda da pista'), ('Não passar por dentro do túnel', 'Não passar por dentro do túnel'), ('Quando o robô não conseguir subir a rampa 30 graus', 'Quando o robô não conseguir subir a rampa'), ('Quando o robô não conseguir descer a rampa 30 graus', 'Quando o robô não conseguir descer a rampa'), ('Não separar ou separar incorretamente algum objeto da zona de coleta seletiva', 'Não separar ou separar incorretamente algum objeto da zona de coleta seletiva'), ('Robô virar de lado ou de ponta cabeça', 'Robô virar de lado ou de ponta cabeça'), ('Robô destruir a pista', 'Robô destruir a pista'), ('Não acessar a Área de Coleta Seletiva', 'Não acessar a Área de Coleta Seletiva'), ('DNS - Did Not Start', 'DNS - Did Not Start')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='penalidade_9',
            field=models.CharField(choices=[('Nenhuma', 'Nenhuma'), ('Tocar o robô', 'Tocar o robô'), ('O robô tocou em qualquer borda da pista', 'O robô tocou em qualquer borda da pista'), ('Não passar por dentro do túnel', 'Não passar por dentro do túnel'), ('Quando o robô não conseguir subir a rampa 30 graus', 'Quando o robô não conseguir subir a rampa'), ('Quando o robô não conseguir descer a rampa 30 graus', 'Quando o robô não conseguir descer a rampa'), ('Não separar ou separar incorretamente algum objeto da zona de coleta seletiva', 'Não separar ou separar incorretamente algum objeto da zona de coleta seletiva'), ('Robô virar de lado ou de ponta cabeça', 'Robô virar de lado ou de ponta cabeça'), ('Robô destruir a pista', 'Robô destruir a pista'), ('Não acessar a Área de Coleta Seletiva', 'Não acessar a Área de Coleta Seletiva'), ('DNS - Did Not Start', 'DNS - Did Not Start')], max_length=50),
        ),
    ]
