# Generated by Django 2.2.6 on 2019-11-20 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0006_auto_20191120_0431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastro',
            old_name='value_penal_1',
            new_name='Valor_da_penalidade_1',
        ),
        migrations.RenameField(
            model_name='cadastro',
            old_name='value_penal_10',
            new_name='Valor_da_penalidade_10',
        ),
        migrations.RenameField(
            model_name='cadastro',
            old_name='value_penal_11',
            new_name='Valor_da_penalidade_11',
        ),
        migrations.RenameField(
            model_name='cadastro',
            old_name='value_penal_2',
            new_name='Valor_da_penalidade_2',
        ),
        migrations.RenameField(
            model_name='cadastro',
            old_name='value_penal_3',
            new_name='Valor_da_penalidade_3',
        ),
        migrations.RenameField(
            model_name='cadastro',
            old_name='value_penal_4',
            new_name='Valor_da_penalidade_4',
        ),
        migrations.RenameField(
            model_name='cadastro',
            old_name='value_penal_5',
            new_name='Valor_da_penalidade_5',
        ),
        migrations.RenameField(
            model_name='cadastro',
            old_name='value_penal_6',
            new_name='Valor_da_penalidade_6',
        ),
        migrations.RenameField(
            model_name='cadastro',
            old_name='value_penal_7',
            new_name='Valor_da_penalidade_7',
        ),
        migrations.RenameField(
            model_name='cadastro',
            old_name='value_penal_8',
            new_name='Valor_da_penalidade_8',
        ),
        migrations.RenameField(
            model_name='cadastro',
            old_name='value_penal_9',
            new_name='Valor_da_penalidade_9',
        ),
    ]
